default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: iss_tracker_development

test:
  <<: *default
  database: iss_tracker_test

production:
  <<: *default
  database: iss_tracker_production
  username: iss_tracker
  password: <%= ENV['ISS_TRACKER_DATABASE_PASSWORD'] %>
